apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ingress-tls-patch.yaml

images:
  - name: devsu-demo-devops-nodejs
    newName: devsudemoacri8sxk5.azurecr.io/devsu-demo-devops-nodejs
    newTag: latest
